name: 🐞 Bug Report
description: Noticed something that doesn't work right?
labels: ["bug"]
assignees:
  - oparisblue
body:
  - type: markdown
    attributes:
      value: Thanks for reporting this issue!
  - type: input
    id: version
    attributes:
      label: What Scaffold version are you using?
      description: You can find this under <insert instructions>
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: In which area are you seeing the issue?
      options:
        - Accounts
        - Device Drivers
        - Desktop Environment / System
        - File Systems
        - File Parsing / Loading
        - Font Rendering
        - General Rendering
        - Hex Editor
        - Opening / Closing Apps
        - Text Entry
        - Transom Compiler
        - UI Components
        - Other (please note where in your report)
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: What type of issue is this?
      options:
        - Incorrect / Unexpected Behaviour
        - Application Crash
        - Application Lag / Unresponsiveness
    validations:
      required: true
  - type: checkboxes
    id: impact
    attributes:
      label: What was the impact of the bug?
      options:
        - label: I lost what I was currently working on (unsaved changes, etc)
        - label: I lost files that I had previously saved, or that exist somewhere else on my mounted drive
        - label: I was not able to complete my overall goal
        - label: Scaffold was left in an unusable / invalid state
        - label: Scaffold was left in an unusable / invalid state, _even after I reloaded_
        - label: It allowed me to do something I shouldn't be able to do
        - label: It has security implications
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: What did you expect to happen?
  - type: textarea
    id: steps
    attributes:
      label: What are the steps to reproduce the bug?
    validations:
      required: true
  - type: textarea
    id: trace
    attributes:
      label: Stack Trace (if given)
  - type: textarea
    id: comments
    attributes:
      label: Anything else you'd like to add?
